In [59]:
import numpy as np
import pandas as pd

np.random.seed(42)

students_df = pd.DataFrame({
    "Student": ["Maya", "Liam", "Sofia", "Noah", "Ava", "Ethan", "Emma", "Lucas", "Olivia", "Arjun"],
    "Math": np.random.randint(70, 101, size=10),
    "Science": np.random.randint(80, 101, size=10),
    "English": np.random.randint(80, 101, size=10)
})

students_df

  Student  Math  Science  English
0    Maya    76       98       85
1    Liam    89       90       81
2   Sofia    98       90      100
3    Noah    84      100       80
4     Ava    80       83       91
5   Ethan    77       87       91
6    Emma    98       82       96
7   Lucas    90      100       89
8  Olivia    76       81       95
9   Arjun    95       91       94

In [60]:
students_df.head(5)
students_df.shape
students_df.dtypes
students_df[["Math","Science","English"]].mean()
students_df[["Math","Science","English"]].max()
students_df[["Math","Science","English"]].min()

Math       76
Science    81
English    80
dtype: int32

In [66]:
students_df["Average"] = students_df[["Math", "Science", "English"]].mean(axis=1).round(2)
students_df[students_df["Average"] >= 90]
students_df[["Math","Science","English","Average"]]

   Math  Science  English  Average
0    76       98       85    86.33
1    89       90       81    86.67
2    98       90      100    96.00
3    84      100       80    88.00
4    80       83       91    84.67
5    77       87       91    85.00
6    98       82       96    92.00
7    90      100       89    93.00
8    76       81       95    84.00
9    95       91       94    93.33

In [75]:
top_students= (
    students_df[students_df["Average"] >= 90]
    [["Math","Science","English","Average"]].sort_values("Average",ascending = False)  
)
top_students

   Math  Science  English  Average
2    98       90      100    96.00
9    95       91       94    93.33
7    90      100       89    93.00
6    98       82       96    92.00

In [83]:
subject_performance_summary = students_df.copy()

In [102]:
subject_performance_summary_flip = subject_performance_summary.T
subject_performance = subject_performance_summary_flip[0:4]

In [109]:
# filename: subject-performance-summary.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

subject_summary = students_df[["Math", "Science", "English"]].agg(
    ["mean", "max", "min"]
).round(2)

subject_summary = subject_summary.rename(
    index={
        "mean": "Average",
        "max": "Highest",
        "min": "Lowest"
    }
)

print(subject_summary)

         Math  Science  English
Average  86.3     90.2     90.2
Highest  98.0    100.0    100.0
Lowest   76.0     81.0     80.0