In [1]:
import pandas as pd 

student_data = {
    "Maya": {"Math": 88, "Science": 92, "English": 85},
    "Liam": {"Math": 76, "Science": 81, "English": 79},
    "Sofia": {"Math": 95, "Science": 89, "English": 93},
    "Noah": {"Math": 84, "Science": 87, "English": 82},
    "Ava": {"Math": 91, "Science": 94, "English": 90}
}

students_df = pd.DataFrame(student_data).T

students_df["Total"] = students_df.sum(axis=1)
students_df["Average"] = students_df[["Math", "Science", "English"]].mean(axis=1).round(2)
students_df["Result"] = "Needs Improvement"
students_df.loc[students_df["Average"] >= 80, "Result"] = "Pass"

students_df

       Math  Science  English  Total  Average             Result
Maya     88       92       85    265    88.33               Pass
Liam     76       81       79    236    78.67  Needs Improvement
Sofia    95       89       93    277    92.33               Pass
Noah     84       87       82    253    84.33               Pass
Ava      91       94       90    275    91.67               Pass

In [2]:
students_df.loc[students_df["Total"]>= 250, "Grade"] = "A+"
students_df.fillna("B+")

       Math  Science  English  Total  Average             Result Grade
Maya     88       92       85    265    88.33               Pass    A+
Liam     76       81       79    236    78.67  Needs Improvement    B+
Sofia    95       89       93    277    92.33               Pass    A+
Noah     84       87       82    253    84.33               Pass    A+
Ava      91       94       90    275    91.67               Pass    A+

In [3]:
students_df["Average"].sort_values(ascending=False)

Sofia    92.33
Ava      91.67
Maya     88.33
Noah     84.33
Liam     78.67
Name: Average, dtype: float64

In [4]:
students_df[["Average", "Result"]].sort_values(by="Average", ascending=False)[0:3]

#sorted_df[0:3]

       Average Result
Sofia    92.33   Pass
Ava      91.67   Pass
Maya     88.33   Pass

In [5]:
students_df

       Math  Science  English  Total  Average             Result Grade
Maya     88       92       85    265    88.33               Pass    A+
Liam     76       81       79    236    78.67  Needs Improvement   NaN
Sofia    95       89       93    277    92.33               Pass    A+
Noah     84       87       82    253    84.33               Pass    A+
Ava      91       94       90    275    91.67               Pass    A+

In [15]:
students_df.groupby("Result")["Average"].mean()

Result
Needs Improvement    78.670
Pass                 89.165
Name: Average, dtype: float64

In [24]:
math_avg = print(students_df["Math"].mean())
science_avg = print(students_df["Science"].mean())
english_avg = print(students_df["English"].mean())

86.8
88.6
85.8

In [25]:
students_df.groupby("Average")[["Math","Science","English"]].mean()

         Math  Science  English
Average
78.67    76.0     81.0     79.0
84.33    84.0     87.0     82.0
88.33    88.0     92.0     85.0
91.67    91.0     94.0     90.0
92.33    95.0     89.0     93.0

In [39]:
# filename: subject-averages.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

subject_averages = students_df[["Math", "Science", "English"]].mean()
subject_averages
highest_average = subject_averages.max()
highest_average
print(f"The highest average is {highest_average}")

The highest average is 88.6

In [48]:
subject_averages = {
    "Math": math_avg,
    "Science": science_avg,
    "English": english_avg
}

highest_average_sub = subject_averages.idxmax()
highest_average = subject_averages.max()

print(f"{highest_average_sub} has the highest average: {highest_average:.2f}")

AttributeError: 'dict' object has no attribute 'idxmax'

In [51]:
highest_subject = max(subject_averages, key=subject_averages.get)
highest_average = subject_averages[highest_subject]
highest_average

np.float64(88.6)

In [52]:
subject_averages

{'Math': np.float64(86.8),
 'Science': np.float64(88.6),
 'English': np.float64(85.8)}